#!/usr/bin/perl -w

use strict;
use utf8;
use DBI;
use Config::Simple;

my %cfg;
Config::Simple->import_from( "/etc/dev95/jwc2ical.conf", \%cfg);

print $cfg{"DB_USER"}, "\n";
print $cfg{"DB_PASSWD"}, "\n";

my $user = $cfg{"DB_USER"};
my $passwd = $cfg{"DB_PASSWD"};
my $dbh = DBI->connect{"DBI:mysql:jwc2ical", $user, $password}
	or die "Couldn't connect to data base: ", DBI->errstr;

my @class_parts = qw/ name teacher location week repeats date s_time t_time/;
my @exam_parts = qw/ week date s_time t_time location name/;
my @sql_parts = qw/ version class name teacher location week date s_time t_time repeats interval type/;
my $sth = $dbh->prepare("INSERT INTO events ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");

my $coures = <STDIN>;
my @coures = split /`/, $coures;

my @classes;
my @exams;
while ( my $line = <STDIN>)
{
	chomp $line;
	my @info = split /`/, $line;
	my $var = $info[0];
	my $vars = $var.'s';
	$vars = $vars eq 'classs' ? 'classes' : $vars;

	my %{$var.'_info'};
	foreach ( 1..@{$var.'_parts'})
	{
		if ( ${$var.'_parts'}[$_-1] =~ m/time/)
		{
			${$var.'_info'}{${$var.'_parts'}[$_-1]} = [ split /:/, $info[$_]];
		}
		else
		{
			${$var.'_info'}{${$var.'_parts'}[$_-1]} = $info[$_];
		}
	}
	my $flag = undef;
	foreach ( @useless)
	{
		${$var.'_info.'}{name} =~ m/$_/ and $flag = 1 and last;
	}
	push @{$vars}, { %{$var.'_info'}} if not $flag;
}

#foreach()
#{
#	foreach()
#	{
#		my $rc = $sth->bind_param( $p_num, $bind_value, $bind_type);
#	}
#	my $rv = $sth->execute;
#	if ( $rv)
#	{
#	}
#	{
#	}
#}


